from enum import Enum


class Tasks(str, Enum):
    # Worker variables
    WORKER_TASK_UNLOAD_MODEL = "UNLOAD"
    WORKER_TASK_EMBEDDING = "EMBEDDING"
    WORKER_TASK_INFERENCE = "INFERENCE"
    WORKER_TASK_VISION_ENCODER = "VISION_ENCODER"
    WORKER_TASK_FINISHED = "<RKLLM_TASK_FINISHED>"
    WORKER_TASK_ERROR = "<RKLLM_TASK_ERROR>"
    WORKER_TASK_ABORT_INFERENCE = "ABORT"
    WORKER_TASK_CLEAR_CACHE = "CLEAR_CACHE"
